name:                AoC2018
version:             0.1.0.0
github:              "fhaust/AoC2018"
license:             BSD3
author:              "Florian Hofmann"
maintainer:          "fho@f12n.de"
copyright:           "MIT"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/fhaust/AoC2018#readme>

dependencies:
- base >= 4.7 && < 5
- vector
- bytestring
- containers


library:
  source-dirs: src

executables:
  AoC2018-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AoC2018

tests:
  AoC2018-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - AoC2018
